name: Playwright E2E Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  playwright-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies and run Playwright tests
        run: |
          cd ubeer  # Change the directory to where package.json is located
          npm install
          npx playwright install
          npm run start &  # Démarre l'application en arrière-plan
          npx wait-on http://localhost:3000  # Attends que le serveur soit prêt (change le port si nécessaire)
          npx playwright test
